[package]
name = "mipidsi"
description = "MIPI Display Command Set compatible generic driver"
version = "0.9.0"
authors = ["Ales Katona <almindor@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/almindor/mipidsi"
keywords = ["embedded-hal-driver", "mipi", "dcs", "display"]
readme = "README.md"
documentation = "https://docs.rs/mipidsi"
rust-version = "1.75"

[dependencies]
#embedded-graphics-core = "0.4.0"
embedded-graphics-core = { path = "../embedded-graphics/core", features = [
    "async_draw",
] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
heapless = "0.8.0"

[dev-dependencies]
#embedded-graphics = "0.8.1"
#embedded-graphics = { path = "../embedded-graphics", features = ["async_draw"] }
embedded-graphics = { git = "https://github.com/TomDeRybel/embedded-graphics.git", features = [
    "async_draw",
] }

[features]
default = ["batch"]
batch = []

[workspace]
members = ["mipidsi-async"]
